// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: link-share.proto

package link_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkState int32

const (
	LinkState_DOWN LinkState = 0
	LinkState_UP   LinkState = 1
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "DOWN",
		1: "UP",
	}
	LinkState_value = map[string]int32{
		"DOWN": 0,
		"UP":   1,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_link_share_proto_enumTypes[0].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_link_share_proto_enumTypes[0]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_link_share_proto_rawDescGZIP(), []int{0}
}

type Helo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipaddr string `protobuf:"bytes,1,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *Helo) Reset() {
	*x = Helo{}
	mi := &file_link_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Helo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Helo) ProtoMessage() {}

func (x *Helo) ProtoReflect() protoreflect.Message {
	mi := &file_link_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Helo.ProtoReflect.Descriptor instead.
func (*Helo) Descriptor() ([]byte, []int) {
	return file_link_share_proto_rawDescGZIP(), []int{0}
}

func (x *Helo) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *Helo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   int32  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Dest string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_link_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_link_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_link_share_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Route) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

type Announce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lstate        LinkState `protobuf:"varint,1,opt,name=lstate,proto3,enum=link_proto.LinkState" json:"lstate,omitempty"`
	Gateway       string    `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Domain        string    `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Nameservers   string    `protobuf:"bytes,4,opt,name=nameservers,proto3" json:"nameservers,omitempty"`
	Searchdomains string    `protobuf:"bytes,5,opt,name=searchdomains,proto3" json:"searchdomains,omitempty"`
	Routes        []*Route  `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *Announce) Reset() {
	*x = Announce{}
	mi := &file_link_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announce) ProtoMessage() {}

func (x *Announce) ProtoReflect() protoreflect.Message {
	mi := &file_link_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announce.ProtoReflect.Descriptor instead.
func (*Announce) Descriptor() ([]byte, []int) {
	return file_link_share_proto_rawDescGZIP(), []int{2}
}

func (x *Announce) GetLstate() LinkState {
	if x != nil {
		return x.Lstate
	}
	return LinkState_DOWN
}

func (x *Announce) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Announce) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Announce) GetNameservers() string {
	if x != nil {
		return x.Nameservers
	}
	return ""
}

func (x *Announce) GetSearchdomains() string {
	if x != nil {
		return x.Searchdomains
	}
	return ""
}

func (x *Announce) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Pkttype:
	//
	//	*Packet_Helo
	//	*Packet_Announce
	Pkttype isPacket_Pkttype `protobuf_oneof:"pkttype"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_link_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_link_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_link_share_proto_rawDescGZIP(), []int{3}
}

func (m *Packet) GetPkttype() isPacket_Pkttype {
	if m != nil {
		return m.Pkttype
	}
	return nil
}

func (x *Packet) GetHelo() *Helo {
	if x, ok := x.GetPkttype().(*Packet_Helo); ok {
		return x.Helo
	}
	return nil
}

func (x *Packet) GetAnnounce() *Announce {
	if x, ok := x.GetPkttype().(*Packet_Announce); ok {
		return x.Announce
	}
	return nil
}

type isPacket_Pkttype interface {
	isPacket_Pkttype()
}

type Packet_Helo struct {
	Helo *Helo `protobuf:"bytes,1,opt,name=helo,proto3,oneof"`
}

type Packet_Announce struct {
	Announce *Announce `protobuf:"bytes,2,opt,name=announce,proto3,oneof"`
}

func (*Packet_Helo) isPacket_Pkttype() {}

func (*Packet_Announce) isPacket_Pkttype() {}

var File_link_share_proto protoreflect.FileDescriptor

var file_link_share_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36,
	0x0a, 0x04, 0x48, 0x65, 0x6c, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2b, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x74, 0x22, 0xde, 0x01, 0x0a, 0x08, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x6c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x22, 0x6f, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x26,
	0x0a, 0x04, 0x68, 0x65, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6f, 0x48, 0x00,
	0x52, 0x04, 0x68, 0x65, 0x6c, 0x6f, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x6b,
	0x74, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x1d, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x55, 0x50, 0x10, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_link_share_proto_rawDescOnce sync.Once
	file_link_share_proto_rawDescData = file_link_share_proto_rawDesc
)

func file_link_share_proto_rawDescGZIP() []byte {
	file_link_share_proto_rawDescOnce.Do(func() {
		file_link_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_share_proto_rawDescData)
	})
	return file_link_share_proto_rawDescData
}

var file_link_share_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_link_share_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_link_share_proto_goTypes = []any{
	(LinkState)(0),   // 0: link_proto.LinkState
	(*Helo)(nil),     // 1: link_proto.Helo
	(*Route)(nil),    // 2: link_proto.Route
	(*Announce)(nil), // 3: link_proto.Announce
	(*Packet)(nil),   // 4: link_proto.Packet
}
var file_link_share_proto_depIdxs = []int32{
	0, // 0: link_proto.Announce.lstate:type_name -> link_proto.LinkState
	2, // 1: link_proto.Announce.routes:type_name -> link_proto.Route
	1, // 2: link_proto.Packet.helo:type_name -> link_proto.Helo
	3, // 3: link_proto.Packet.announce:type_name -> link_proto.Announce
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_link_share_proto_init() }
func file_link_share_proto_init() {
	if File_link_share_proto != nil {
		return
	}
	file_link_share_proto_msgTypes[3].OneofWrappers = []any{
		(*Packet_Helo)(nil),
		(*Packet_Announce)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_share_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_link_share_proto_goTypes,
		DependencyIndexes: file_link_share_proto_depIdxs,
		EnumInfos:         file_link_share_proto_enumTypes,
		MessageInfos:      file_link_share_proto_msgTypes,
	}.Build()
	File_link_share_proto = out.File
	file_link_share_proto_rawDesc = nil
	file_link_share_proto_goTypes = nil
	file_link_share_proto_depIdxs = nil
}
